### ISSUE TITLE
BWA Indexing does not run correctly

### ISSUE THREAD

**Issue by jfy133** [apeltzer/EAGER-CLI#47]
When running EAGER-CLI 1.92.21 and the reference does not have the `bwa index` related files, the run crashes.

I believe EAGER is meant to include the functionality to generate the index files for you, but correct me if I'm wrong.

```
################
#[bwa_aln] 17bp reads: max_diff = 2
[bwa_aln] 22bp reads: max_diff = 3
[bwa_aln] 42bp reads: max_diff = 4
[bwa_aln] 64bp reads: max_diff = 5
[bwa_aln] 90bp reads: max_diff = 6
[bwa_aln] 117bp reads: max_diff = 7
[bwa_aln] 146bp reads: max_diff = 8
[bwa_aln] 176bp reads: max_diff = 9
[bwa_aln] 207bp reads: max_diff = 10
[bwa_aln] 239bp reads: max_diff = 11
[bwa_aln] fail to locate the index
```

**Comment by apeltzer** [comment]
If I understand correctly: You did specify a FastA reference genome but that one doesn't have (yet) appropriate index files right? 
In this case, EAGER-CLI should be able to create the indices on the fly in the very first run and use them for multiple samples automatically. I'll have a look...

**Comment by jfy133** [comment]
Exactly. I myself didn't run this myself rather than a colleague, but I seem to remember I had the same issue in the past.

Let me know if you can't reproduce it and I'll ask my colleague for more details.

**Comment by apeltzer** [comment]
Hi! 

closing all issues here, as the new eager pipeline will be a successor to this and hopefully resolve all of the issues above. 
Please use that instead :-) 

https://github.com/nf-core/eager
