### ISSUE TITLE
Clean up does not occur even if pipeline crashes (v1.92.55)

### ISSUE THREAD

**Issue by jfy133** [apeltzer/EAGER-CLI#48]
I just ran a large of number of jobs in EAGERCLI v1.92.55 where I had accidentally left the 'organism' as Human rather than bacterial (which reference I was mapping to).

When the pipeline reached mttonuclearratio calculations, the pipeline crashed as it could not find the default specified mitochondrial chromosome name in the reference/idxstats. As it crashed, the rest of the subsequent modules were not run (CleanUp, Create Report?, etc.)

As a byproduct of this crashing, I was left with 8.6TB of results directories that had not been CleanUp, such as large intermediate SAM files etc..

It would be useful for a more sophisticated cleanup system to be implemented, to ensure that for new users (to both EAGER and informatics) who aren't familiar with the command line with checking their output directories. For example running clean up on a specific module directory after the subsequent module completed successfully, rather than waiting until the end. 

This restart the EAGER run from the last successful module without re-running the whole thing, but without having a large HDD footprint of the earlier (successful) intermediate steps until you have realised you need to re-run it.

**Comment by apeltzer** [comment]
Hi James!

thanks for this hint - I probably won't introduce that in the regular EAGER version out there, but maybe in the nextflow based EAGER 2.X development branch, as this would require quite dramatic changes in the underlying model of EAGER-CLI.

**Comment by apeltzer** [comment]
Hi! 

closing all issues here, as the new eager pipeline will be a successor to this and hopefully resolve all of the issues above. 
Please use that instead :-) 

https://github.com/nf-core/eager

**Comment by jfy133** [comment]
Oh cool! I've not heard of that. I'll check it out ;)
