### ISSUE TITLE
EAGERerrorSystem

### ISSUE THREAD

**Issue by apeltzer** [apeltzer/EAGER-CLI#5]
Either combine execution.log and log.log, or in log.log include the command ran before STDOUT is printed. Additionally do not generate 'DONE' files if an error occurs

**Comment by jfy133** [comment]
A further improvement could be to include at the beginning of the output logs the EAGERCLI and EAGER-GUI version that is being used in that run.

**Comment by apeltzer** [comment]
Hi! I just added this as this is pretty easy to fix - will work in the next upcoming version update. However, this only makes sense in the EAGER-CLI component as the GUI part is not producing anything else than a XML file, which is not as easy to upgrade .

**Comment by apeltzer** [comment]
Closing this, Stephen has fixed that pretty long time ago :-)

**Comment by jfy133** [comment]
The eager version has been implemented, but not the original suggestion of including the command being executed before the corresponding stdout being printed.

I am still sometimes finding it difficult to trace back to which step is causing an error, as the programs used in the pipeline themselves are also not very good as making themselves 'visible'.

For example, here it is not clear which stdout is associated with which module (e.g. is DEBUG related to DeDup, or related to the BamQC? or something else?):

```
Picked up JAVA_TOOL_OPTIONS: -Djava.io.tmpdir=<PATH_TO>/5-DeDup/.tmp
DeDup v0.11.4
DEBUG   2016-11-07 14:10:49 BlockCompressedOutputStream Using deflater: Deflater
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=1024m; support was removed in 8.0
Failed to run bamqc
java.lang.RuntimeException: The BAM file is empty or corrupt
    at org.bioinfo.ngs.qc.qualimap.process.BamStatsAnalysis.run(BamStatsAnalysis.java:508)
    at org.bioinfo.ngs.qc.qualimap.main.BamQcTool.execute(BamQcTool.java:236)
    at org.bioinfo.ngs.qc.qualimap.main.NgsSmartTool.run(NgsSmartTool.java:187)
    at org.bioinfo.ngs.qc.qualimap.main.NgsSmartMain.main(NgsSmartMain.java:111)
```

What I think would be clearer, would be along the lines of:

```
+++ Running DeDup (or the command itself) +++

Picked up JAVA_TOOL_OPTIONS: -Djava.io.tmpdir=/projects1/calculus_microbiome/evolution/eager/Propionibacterium_propionicum/shallow/LB1/5-DeDup/.tmp
DeDup v0.11.4

+++ Running BamQC (or the command itself) )+++

DEBUG   2016-11-07 14:10:49 BlockCompressedOutputStream Using deflater: Deflater
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=1024m; support was removed in 8.0
Failed to run bamqc
java.lang.RuntimeException: The BAM file is empty or corrupt
    at org.bioinfo.ngs.qc.qualimap.process.BamStatsAnalysis.run(BamStatsAnalysis.java:508)
    at org.bioinfo.ngs.qc.qualimap.main.BamQcTool.execute(BamQcTool.java:236)
    at org.bioinfo.ngs.qc.qualimap.main.NgsSmartTool.run(NgsSmartTool.java:187)
    at org.bioinfo.ngs.qc.qualimap.main.NgsSmartMain.main(NgsSmartMain.java:111)

This would then greatly speeding up finding which command is the culprit, when the run fails. 
```

Also by combining the log.log and execution.log will reduce the number of output files.

**Comment by apeltzer** [comment]
Ok, got it - I think this will not be too easy due to the nature of both file(s) (problematic could be that the applications are loggin through Java ProcessBuilder and the execution_log is something specifically written out by my own implementation and I don't know whether concurrent access is possible with these.

**Comment by jfy133** [comment]
No problem, this isn't an important issue, just to help in debugging ;) ! If it was possible to just print a new line between each stdout that would already help a lot (then you can count the number of 'blocks' and compare to the execution log).

**Comment by apeltzer** [comment]
I have a working update now for this, looking like that and would greatly improve readability / trackability of that behaviour in EAGER: 

`
BWAMem was executed with the following commandline:
/bin/sh -c bwa mem -t 4 /share/projects/Arora/Syphilis/reference_genomes/nichols/NC_021490.2.fasta /home/peltzer/palshare/peltzer/2017-04-17_AREAGERTest/Syphilis_Comparision_Study/Results-PE-Merging/C27/1-ClipAndMerge/C27_L001_R1_001.combined.fq.gz > /home/peltzer/palshare/peltzer/2017-04-17_AREAGERTest/Syphilis_Comparision_Study/Results-PE-Merging/C27/3-Mapper/C27_L001_R1_001.combined.fq.bwamem.sam
---------------
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::process] read 449306 sequences (40000121 bp)...
[M::process] read 446680 sequences (40000169 bp)...`

(same for each issues command in the pipeline, if there is any output coming from the subsequent tool this will be integrated here, too). 

I introduced the ----- part to make it easier to read for users. Also the runtime information is now included, too - so you can also use the EAGER.log (<- new name to make this more visible for users) to track down runtime for your run, too. 

I think this is quite useful.
